project:
  type: website
  lib-dir: site_libs
  pre-render: scripts/pre_render.R
  post-render: scripts/post_render.R
  render:
    - index.qmd
    - vignettes/eval_hhs_vs_doctor_visits_api_state.qmd
    - vignettes/eval_confirmed_incidence_num_vs_doctor_visits_api_county.qmd
  resources:
    - "indicator_analysis/comp_hhs_vs_doctor_visits_api_state.html"
    - "indicator_analysis/eval_doctor_visits_smoothed_adj_cli_api_state.html"
    - "indicator_analysis/eval_jhu_csse_vs_doctor_visits_api_county.html"
    - "indicator_analysis/eval_doctor_visits_smoothed_adj_cli_api_county.html"
    - "revision_analysis/revision_hospital_admissions_smoothed_covid19_from_claims_api_state.html"
    - "dataset_comparison/dataset_comparison_dv.html"

execute:
  freeze: false

editor: source

website:
  title: "RAT SCAN"
  navbar:
    pinned: false
    title: "<i class='bi bi-journal-text'></i> RAT SCAN"
    right:
      - text: Indicators
        menu:
          - text: "County: Dr. Visits"
            href: indicator_analysis/eval_confirmed_incidence_num_vs_doctor_visits_api_county.html
          - text: "State: HHS vs Dr. Visits"
            href: indicator_analysis/eval_hhs_vs_doctor_visits_api_state.html
      - text: Revisions
        menu:
          - text: "State: COVID-19 Hospital Admissions"
            href: revision_analysis/revision_hospital_admissions_smoothed_covid19_from_claims_api_state.html
      - text: ETL Comparison
        menu:
          - text: "HRR: Old vs New Pipeline Claims (DV)"
            href: dataset_comparison/dataset_comparison_dv.html
      - icon: github

format:
  html:
    theme: [cosmo, assets/styles.scss]
