project:
  type: website
  lib-dir: site_libs
  pre-render: scripts/pre_render.R
  render:
    - index.qmd

execute:
  freeze: false

editor: source

website:
  title: "Rapid SCAN (Tentative)"
  navbar:
    pinned: false
    title: "<i class='bi bi-journal-text'></i> Rapid SCAN (Tentative)"
    right:
      - text: Indicators
        menu:
          - text: "County: JHU COVID-19 Cases vs Dr. Visits"
            href: indicator_analysis/eval_jhu_csse_vs_doctor_visits_api_county.html
          - text: "County: Dr. Visits"
            href: indicator_analysis/eval_confirmed_incidence_num_vs_doctor_visits_api_county.html
          - text: "State: HHS vs Dr. Visits"
            href: indicator_analysis/eval_hhs_vs_doctor_visits_api_state.html
      - text: Revisions
        menu:
          - text: "State: COVID-19 Hospital Admissions"
            href: revision_analysis/revision_hospital_admissions_smoothed_covid19_from_claims_api_state.html
      - text: ETL Comparison
        menu:
          - text: "HRR: Old vs New Pipeline Claims (DV)"
            href: dataset_comparison/dataset_comparison_dv.html
      - icon: github

format:
  html:
    theme: [cosmo, assets/styles.scss]
